security:
    enable_authenticator_manager: true

    providers:
        predefined_user_provider:
            memory:
                users:
                    test_user:
                        password: 'Paysera123!'
                        roles: [ 'ROLE_USER' ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/auth/login
            security: false

        api:
            pattern: ^/.*
            stateless: true
            provider: predefined_user_provider
            access_token:
                token_handler: App\Security\AccessTokenHandler
                failure_handler: App\Security\FailureHandler
            access_denied_handler: App\Security\AccessDeniedHandler
            entry_point: App\Security\AuthenticationEntryPoint

        index:
            pattern: ^/$
            security: false

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
