version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_app
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
      - DATABASE_URL=postgresql://symfony:symfony@postgres:5432/symfony?serverVersion=15&charset=utf8
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
      chown -R root:www-data /var/www/html &&
      composer install &&
      php bin/console cache:warmup &&
      php bin/console doctrine:database:create --if-not-exists &&
      php bin/console doctrine:schema:update --force &&
      php bin/console paysera:app:refresh-db &&
      php-fpm"

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:15
    container_name: symfony_postgres
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
